# Generated by Django 2.2.16 on 2022-10-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
